# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 17:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='egg',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
