# Generated by Django 2.0.1 on 2018-01-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180119_1210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.IntegerField(default=0, verbose_name='客户端ID')),
                ('project_name', models.CharField(max_length=255, verbose_name='项目名字')),
                ('spider_name', models.CharField(max_length=255, verbose_name='Spider名字')),
                ('scheduler_at', models.IntegerField(default=0, verbose_name='调度间隔时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='上一次调度时间')),
                ('success', models.BooleanField(default=False, verbose_name='是否调度成功')),
            ],
            options={
                'verbose_name': '调度',
            },
        ),
    ]
