# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-08 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_project_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='configurable',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
