# Generated by Django 2.0.1 on 2018-01-25 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_scheduler'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='job_id',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='调度返回的作业ID'),
        ),
    ]
