from django.conf.urls import url
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('api/index/status/', views.index_status, name='index_status'),
    path('api/client/', views.client_index, name='client_index'),
    path('api/client/create', views.client_create, name='client_create'),
    path('api/client/<int:client_id>/', views.client_info, name='client_info'),
    path('api/client/<int:client_id>/status/', views.client_status, name='client_status'),
    path('api/client/<int:client_id>/update', views.client_update, name='client_update'),
    path('api/client/<int:client_id>/remove/', views.client_remove, name='client_remove'),
    path('api/client/<int:client_id>/projects', views.project_list, name='project_list'),
    path('api/client/<int:client_id>/project/<slug:project_name>/spiders', views.spider_list, name='spider_list'),
    path('api/client/<int:client_id>/project/<slug:project_name>/spider/<slug:spider_name>/job/<slug:job_id>/log',
         views.job_log, name='job_log'),
    path('api/client/<int:client_id>/project/<slug:project_name>/spider/<slug:spider_name>/', views.spider_start,
         name='spider_start'),
    path('api/client/<int:client_id>/project/<slug:project_name>/jobs', views.job_list, name='job_list'),
    path('api/client/<int:client_id>/project/<slug:project_name>/version', views.project_version,
         name='project_version'),
    path('api/client/<int:client_id>/project/<slug:project_name>/deploy', views.project_deploy, name='project_deploy'),
    path('api/client/<int:client_id>/project/<slug:project_name>/job/<slug:job_id>/cancel', views.job_cancel,
         name='job_cancel'),
    path('api/project/index', views.project_index, name='project_index'),
    path('api/project/create', views.project_create, name='project_create'),
    path('api/project/<slug:project_name>/configure', views.project_configure, name='project_configure'),
    path('api/project/<slug:project_name>/build', views.project_build, name='project_build'),
    path('api/project/<slug:project_name>/generate', views.project_generate, name='project_generate'),
    path('api/project/<slug:project_name>/tree', views.project_tree, name='project_tree'),
    path('api/project/<slug:project_name>/remove', views.project_remove, name='project_remove'),
    path('api/project/file/rename', views.project_file_rename, name='project_file_rename'),
    path('api/project/file/delete', views.project_file_delete, name='project_file_delete'),
    path('api/project/file/create', views.project_file_create, name='project_file_create'),
    path('api/project/file/update', views.project_file_update, name='project_file_update'),
    path('api/project/file/read', views.project_file_read, name='project_file_read'),
    path('api/monitor/create', views.monitor_create, name='monitor_create'),
    path('api/monitor/db/list', views.monitor_db_list, name='monitor_db_list'),
    path('api/monitor/collection/list', views.monitor_collection_list, name='monitor_collection_list'),
]
