exports.index = '/api/client'
exports.show = '/api/client/:id'
exports.update = '/api/client/:id/update'
exports.projects = '/api/client/:id/projects'
exports.projectSpiders = '/api/client/:id/spiders/:project'
