exports.index = '/api/client'
exports.show = '/api/client/:id'
exports.update = '/api/client/:id/update'
exports.projects = '/api/client/:id/projects'
exports.listSpiders = '/api/client/:id/project/:project/spiders'
exports.startSpider = '/api/client/:id/project/:project/spider/:spider'
exports.listJobs = '/api/client/:id/project/:project/jobs'
